---
title: "Technical specifications"
author: "Ajmal O., Pachka H., Laura T., Lulla O."
date: "08/02/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Modelling
- [x] Population dynamics: multilevel metapopulation - multiwards with caregiver flow and subpopulations structured in patients and caregivers
- [x] Disease dynamics: 3 levels of immunity and seven epidemiological stages
- [x] introduction through visitors
- [x] caregivers contamination in community
- [ ] add patient transfer option
- [ ] add weighted transmission in function of epidemiological stage (variable levels of excretion)
- [ ] add weighted transmission in function of immunity level (variable levels of excretion)

### To review:

- [ ] weight caregivers contamination in community (by the time spent outside the healthcare facility) >> possibility to set to zero

### Surveillance and control strategies
- [x] screening area at the admission
- [x] contact restriction (Covid unit in the ward) for individuals tested positive
- [x] regular screening test for patients
- [x] regular screening test for HCWS
- [ ] variable levels of contact restriction
- [ ] antigenic test of visitors

## ShinyApp

### Dev:

- [ ] add waiting popup window during valueboxoutputModule
- [ ] add pre-build model (see SimInf function)

### Inputs
#### Facility structure
- [x] number of wards
- [x] number of patients per ward
- [x] number of HCWS per wards
- [x] average daily number of visitors per ward
- [x] average length of stay by ward (days)

#### Epidemiological parameters

- [ ] provide a baseline for diff variants of SARS-CoV-2 
- [ ] link to public data for prev in community?

### Outputs
* Network representation
* Incidence patient and health care workers (middle and severe)
* Number of tests
* Probability of outbreak per ward
* Comparison of 2 Surveillance/Control strategies
* Comparaison différentes prévalences en communauté ?

## Publication
### Journals
* Computer Methods and Programs in Biomedicine : https://www.journals.elsevier.com/computer-methods-and-programs-in-biomedicine (IF: 5.428)
* section "Software" de PLOS Computational Biology https://collections.plos.org/collection/software/ (IF: 4.475)
* section "Tools and resources" dans eLife https://elifesciences.org/articles/tools-resources (IF: 8.14)
* application note in bioinformatics https://academic.oup.com/bioinformatics/pages/instructions_for_authors#Types%20of%20Manuscript (IF: 6.937)
* BMC Medical Research Methodology https://bmcmedresmethodol.biomedcentral.com/ (IF: 4.615)
* BMC Bioinformatics https://bmcbioinformatics.biomedcentral.com/ (IF: 3.169)
